version: '3'
services:
  web:
    container_name: ${WEB_HOST}
    image: odoo
    build: ./
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo-web:/var/lib/odoo
    #command: odoo -u estate -d garrido --dev xml
    #restart: always
  db:
    container_name: ${DB_HOST}
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - odoo-db:/var/lib/postgresql/data/pgdata
    restart: always

volumes:
  odoo-db:
  odoo-web:
